import Head from 'next/head';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1 className='rounded-lg bg-primary-300 font-black underline dark:bg-primary-500'>
        Hello! I'm Roxiq
        </h1>
    </>
  );
}
